services:
  - type: web
    name: food-nlp-search
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements-base.txt
      pip install -r requirements-ml.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: LOG_LEVEL
        value: INFO
    healthCheckPath: /health
    autoDeployTrigger: commit 